---
title: "Be a data scientist!"
output: 
    html_document: 
     css: "./project.css"
     toc: true
     toc_float: true
     fig_caption: false
---

Peer feedback due **Date, Time**

Report, slides, and repository due **Date, Time**

Presentation videos due **Date, Time** 

# Introduction

**TLDR**: Pick (or create) a dataset and do something with it. That is your 
final project.

The final project for this class will consist of analysis on a dataset of your 
own choosing or creation. The dataset may already exist, or you may collect your 
own data using a survey, by conducting an experiment, or by scraping the web. 
You can choose the data based on your interests or based on work in other
courses or research projects. The goal of this project is for you to demonstrate 
proficiency in the techniques we have covered in this class (and beyond, if you 
like) and apply them to a dataset in a meaningful way.

# Brief project logistics

The final project will be done with your lab groups.

The four deliverables for the final project are

- A written, reproducible report detailing your analysis
- A GitHub repository corresponding to your report
- A brief set of slides that correspond to your intended oral presentation 
(ten minutes), which must be recorded and uploaded to PLATFORM. All group 
members must present.
- Formal peer review of another team's project

**No late projects are accepted.**

The grade breakdown is as follows:

Total                                                   | 115 pts
--------------------------------------------------------|--------
**Written report**                                      | 60 pts
**Slides**                                              | 15 pts
**Repository**                                          | 5 pts
**Video presentation**                                  | 15 pts
**Overall neatness and presentation style**             | 5 pts
**Peer feedback**                                       | 15 pts

# Data sources

In order for you to have the greatest chance of success with this project it is 
important thatyou choose a manageable dataset. This means that the data should 
be readily accessible and large enough that multiple relationships can be 
explored. As such, your dataset must have at least 50 observations and at  
least 10 variables (exceptions can be made but you must speak with me first). 
The dataset’s variables should include categorical variables, discrete numerical 
variables, and continuous numerical variables.

All analyses must be done in RStudio, and your final written report and 
analysis **must be reproducible**. This means that you must create an R Markdown
document attached to a GitHub repository that will create your written report
exactly upon knitting.

If you are using a dataset that comes in a 
format that we haven't encountered in class (for instance, a `.DAT` file), make 
sure that you are able to load it into RStudio as this can be tricky depending 
on the source. If you are having trouble, ask for help before it is too late.

**Reusing datasets from class:** Do not reuse datasets used in examples / homework 
in the class. 

Some resources that may be helpful:

- [R Data Sources for Regression Analysis](https://rfun.library.duke.edu/blog/data-sources-for-regression-analysis/)
- [kaggle](https://www.kaggle.com/datasets)
- [FiveThirtyEight data](https://data.fivethirtyeight.com/)
- [TidyTuesday](https://github.com/rfordatascience/tidytuesday)


Additions:

- [World Health Organization](https://www.who.int/gho/database/en/)
- [The National Bureau of Economic Research](https://data.nber.org/data/)
- [International Monetary Fund](https://data.imf.org/?sk=388DFA60-1D26-4ADE-B505-A05A558D9A42&sId=1479329328660)
- [General Social Survey](http://gss.norc.org/)
- [United Nations Data](http://data.un.org/)
- [United Nations Statistics Division](https://unstats.un.org/home/)
- [U.K. Data](https://data.gov.uk/)
- [U.S. Data](https://www.data.gov/)
- [U.S. Census Data](https://www.census.gov/data.html)
- [European Statistics](https://ec.europa.eu/eurostat/)
- [Statistics Canada](https://www.statcan.gc.ca/eng/start)
- [Pew Research](https://www.pewresearch.org/download-datasets/)
- [UNICEF](https://data.unicef.org/)
- [CDC](https://www.cdc.gov/datastatistics/index.html)
- [World Bank](https://datacatalog.worldbank.org/)
- [Election Studies](https://electionstudies.org//)

# Project components

## Written report

Your written report must be done using R Markdown. All team members must 
contribute to the GitHub repository, with regular meaningful commits/pushes. 
Before you finalize your write up, make sure the printing of code chunks is 
turned off with the option `echo = FALSE`. 

Your final report must match your GitHub repository *exactly*. The mandatory
components of the report are as follows, but feel free to expand with additional
sections as necessary. There is no page limit or requirement -- however, you
must comprehensively address all aspects below. Please be judicious in what you
decide to include in your final write-up.

The written report is worth 60 points, broken down as

Total                                                   | 60 pts
--------------------------------------------------------|--------
**Introduction/data**                                   | 10 pts
**Methodology**                                         | 20 pts
**Results**                                             | 20 pts
**Discussion**                                          | 10 pts

#### Introduction and data

The introduction should introduce your general research question and your data 
(where it came from, how it was collected, what are the cases, what are the 
variables, etc.). 

#### Methodology 

The methodology section should include the variables used to address your 
research question, as well as any useful visualizations or summary statistics.
As well, you should introduce and justify the statistical method(s) that you 
believe will be useful in answering your research question. 

#### Results 

Showcase how you arrived at answers to 
your question using any techniques we have learned in this class (and some 
beyond, if you're feeling adventurous). Provide the main results from your
analysis. The goal is not to do an exhaustive 
data analysis (i.e., do not calculate every statistic and procedure you have 
learned for every variable), but rather let me know that you are proficient at 
asking meaningful questions and answering them with results of data analysis, 
that you are proficient in using R, and that you are proficient at interpreting 
and presenting the results. Focus on methods that help you begin to answer your 
research questions. 

#### Discussion

This section is a conclusion and discussion. This will require a 
summary of what you have learned about your research question along with 
statistical arguments supporting your conclusions. Also, critique your own 
methods and provide suggestions for improving your analysis. Issues pertaining 
to the reliability and validity of your data and appropriateness of the 
statistical analysis should also be discussed here. A paragraph on what you 
would do differently if you were able to start over with the project or what you 
would do next if you were going to continue work on the project should also be 
included.

## Repository

In addition to your Gradescope submissions, we will be checking your GitHub 
repository. This repository should be contributed to equally by all team members
and should include

- RMarkdown file (formatted to clearly present all of your code and results)
that will output the proposal and write-up in one document
- Meaningful README file on the GitHub repository that contains a *codebook*
for relevant variables
- Dataset(s) (in csv or RData format, in a `/data` folder)
- Presentation (if using Keynote/PowerPoint/Google Slides, export to PDF and put 
in repo, in a `/presentation` folder)

Style and format does count for this assignment, so please take the time to make 
sure everything looks good and your data and code are properly formatted.

## Slides

In addition to the write-up, your team must also create presentation
slides that summarize and showcase your project. Introduce your research question 
and dataset, showcase visualizations, and provide some conclusions. These slides
should serve as a brief visual accompaniment to your write-up and will be graded 
for content and quality. For submission, convert these slides to a .pdf document
to be submitted to Gradescope.

## Peer feedback

Critically reviewing others' work is a crucial part of the scientific process,
and STA 199 is no exception. You will be assigned a team to review. As part of
the review process, you must provide your partner team a copy of your current
report by **DATE, TIME**. After giving the report to your partner team, they
will have a week (i.e., until **DATE, TIME**) to provide a detailed critique
about the written report and data analysis. This feedkback is intended to help
you create a high quality final project, as well as give you experience 
reading and constructively critiquing the work of others.

During the peer feedback process, you will be provided read-only access to your 
partner team's GitHub repo. Provide your feedback in the form of GitHub issues
to your parter team's GitHub repo. 

Peer feedback will be graded on the extent to which it comprehensively and
constructively addresses the components of the partner team's report: the 
research context and motivation, exploratory data analysis, and any inference,
modeling, or conclusions. You must have at least some of these results
available for your partner team to review.

## Presentation

Sometime before **DATE, TIME**, you/your group will upload a video presentation
of your project to Warpwire. Note that all members must present, and that a 
ten-minute time limit is **strictly enforced**.

For the presentation, you can speak over your slide deck, similar to the lecture 
content videos. I recommend using Zoom to record your presentation; however, you 
can use whatever platform works best for your group. Below are a few resources 
to help you record video presentations:

- [Recording presentations in Zoom](https://kb.siue.edu/61721)
- [Apple Quicktime for screen recording]( https://support.apple.com/en-gb/guide/quicktime-player/qtp97b08e666/mac)
- [Windows 10 built-in screen recording functionality](https://www.youtube.com/watch?v=OfPbr1mRDuo)
- [Kap for screen recording](https://getkap.co/)

You will post the presentation video in Warpwire, which is accessible from the 
the course Sakai site (bottom of the left-hand tool bar). To post your video on 
Warpwire:
- Click the Warpwire tab in the course Sakai site.
- Click the “+” and select “Upload files”.
- Locate the video on your computer and click to upload.
- Once you’ve uploaded the video to Warpwire, click to share the video and make
a copy of the video’s URL. You will need this when you post the video in the 
discussion forum.

# Overall notes

The project is very open ended. For instance, in creating a compelling 
visualization(s) of your data in R, there is no limit on what tools or 
packages you may use. You do not need to visualize all of the data at once. A 
single high quality visualization will receive a much higher grade than a large 
number of poor quality visualizations.

Before you finalize your write up, make sure the printing of code chunks is 
turned off with the option `echo = FALSE`. 

Finally, pay attention to details in your write-up and presentation. Neatness, 
coherency, and clarity will count.


# Tips

- Ask questions if any of the expectations are 
unclear.

- *Code*: In your write up your code should be hidden (`echo = FALSE`) so that 
your document is neat and easy to read. However your document should include 
all your code such that if I re-knit your Rmd file I should be able to obtain 
the results you presented. **Exception:** If you want to highlight something 
specific about a piece of code, you're welcome to show that portion. 

- Merge conflicts will 
happen, issues will arise, and that’s fine! Commit and push often, and ask 
questions when stuck.

- Make sure each team member is contributing, both in terms of quality and 
quantity of contribution (we will be reviewing commits from different team 
members).

- All team members are 
expected to contribute equally to the completion of this assignment and group 
assessments will be given at its completion - anyone judged to not have 
sufficient contributed to the final product will have their grade penalized. 
While different teams members may have different backgrounds and abilities, it 
is the responsibility of every team member to understand how and why all code 
and approaches in 
the assignment works.

# Grading

Grading of the project will take into account the following:

- Content - What is the quality of research and/or policy question and relevancy 
of data to those questions?
- Correctness - Are statistical procedures carried out and explained correctly?
- Writing and Presentation - What is the quality of the statistical presentation, 
writing, and explanations?
- Creativity and Critical Thought - Is the project carefully thought out? Are the 
limitations carefully considered? Does it appear that time and effort went into 
the planning and implementation of the project?

A general breakdown of scoring is as follows:

- *90%-100%*: Outstanding effort. Student understands how to apply all statistical 
concepts, can put the results into a cogent argument, can identify weaknesses in 
the argument, and can clearly communicate the results to others.
- *80%-89%*: Good effort. Student understands most of the concepts, puts together 
an adequate argument, identifies some weaknesses of their argument, and communicates 
most results clearly to others.
- *70%-79%*: Passing effort. Student has misunderstanding of concepts in several 
areas, has some trouble putting results together in a cogent argument, and communication 
of results is sometimes unclear.
- *60%-69%*: Struggling effort. Student is making some effort, but has misunderstanding 
of many concepts and is unable to put together a cogent argument. Communication 
of results is unclear.
- *Below 60%*: Student is not making a sufficient effort.

# Peer evaluation

You will be asked to fill out a survey where you rate the contribution and 
teamwork of each team member by assigning a contribution percentage for each 
team member. Filling out the survey is a prerequisite for getting credit on the 
team member evaluation. If you are suggesting that an individual did less than 
half the expected contribution given your team size (e.g., for a team of four
students, if a student contributed less than 12.5% of the total effort), please
provide some explanation. If any individual gets an average peer score 
indicating that this was the case, their grade will be assessed accordingly.

# Late work policy

**There is no late work accepted on this project.** Be sure to turn in your 
work early to avoid any technological mishaps.
